spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri:
          search-paths: configs
          username:
          password:
        label: master
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zone: http:localhost:8761/eureka