spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/itwhongww/h2w.git
          search-paths: config/src/main/resources
          username: itwhongww
          password: hong198954
        label: master
server:
  port: 8888
eureka:
  client:
    service-url:
      default-zone: http:localhost:8761/eureka